# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [1]:
j = 2.0
h = 3.0
i = 5.0

result_a= j + h / i
print(result_a)

2.6


In [2]:
result_b = (j + 10.2) - 5.0 * 2.0
print(result_b)

2.1999999999999993


In [3]:
result_c = j/h+33.8
print(result_c)

34.46666666666666


In [4]:
result_d = j/(h+i)
print(result_d)

0.25


In [5]:
i = result_d
result_e = i*2
print(result_e)

0.5


## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [ ]:
lista_a = [2.0, 3.0, 5.0]
lista_b = [10, 20, 30]

result_a_2 = lista_a + lista_b
print(result_a_2)

[2.0, 3.0, 5.0, 10, 20, 30]


In [ ]:
result_b_2 = lista_a * 2
print(result_b_2)

[2.0, 3.0, 5.0, 2.0, 3.0, 5.0]


In [ ]:
result_c_2 = lista_a + lista_b
print(result_c_2)

[2.0, 3.0, 5.0, 10, 20, 30]


In [ ]:
import numpy as np
lista_a = [2.0, 3.0, 5.0]
lista_b = [10, 20, 30]
lista_c = [1, 2, 3]
array_a = np.array(lista_a)
array_b = np.array(lista_b)
array_c = np.array(lista_c)

result_d_2 = array_a / (array_b * array_c)
print(result_d_2)

[0.2        0.075      0.05555556]


## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [ ]:
import math
a = 2.6
b = 2.2
c = 34.467
d = 0.25
e = 0.5
lista_1 = [a, b, c, d, e]
lista_2 = [math.sqrt (item) for item in lista_1]
lista_3 = lista_1 + lista_2
print(lista_3)

[2.6, 2.2, 34.467, 0.25, 0.5, 1.61245154965971, 1.4832396974191326, 5.87086024360996, 0.5, 0.7071067811865476]


## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [7]:
import numpy as np
lista_3 = [2.6, 2.2, 34.467, 0.25, 0.5, 1.61245154965971, 1.4832396974191326, 5.87086024360996, 0.5, 0.7071067811865476]
lista_duplicada = lista_3 + lista_3
meu_array = np.array(lista_duplicada)
meu_array_final = meu_array.reshape(5, 4)
print(meu_array_final)

[[ 2.6         2.2        34.467       0.25      ]
 [ 0.5         1.61245155  1.4832397   5.87086024]
 [ 0.5         0.70710678  2.6         2.2       ]
 [34.467       0.25        0.5         1.61245155]
 [ 1.4832397   5.87086024  0.5         0.70710678]]


## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [ ]:
import numpy as np
meu_array = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [15,25,35,45],
    [55,65,75,85],
    [12,22,32,42]
])
medias_colunas = np.mean(meu_array, axis=0)
listas_medias = medias_colunas.tolist()
print(listas_medias)

[28.4, 38.4, 48.4, 58.4]


## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [ ]:
import numpy as np
meu_array = np.array([
    [2.6, 2.2, 34.46, 0.25],
    [0.5, 1.61, 1.48, 5.87],
    [0.5, 0.70, 2.6, 2.2],
    [34.46, 0.25, 0.5, 1.61],
    [1.48, 5.87, 0.5, 0.70]
])
lista_medias = [7.908, 2.126, 7.908, 2.126]
geometria = meu_array.shape
total = meu_array.size
array_atualizado = np.vstack([meu_array, lista_medias])
print (array_atualizado)

[[ 2.6    2.2   34.46   0.25 ]
 [ 0.5    1.61   1.48   5.87 ]
 [ 0.5    0.7    2.6    2.2  ]
 [34.46   0.25   0.5    1.61 ]
 [ 1.48   5.87   0.5    0.7  ]
 [ 7.908  2.126  7.908  2.126]]


## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [ ]:
import pandas as pd
array_remodelado = array_atualizado.reshape(-1,4)
df = pd.DataFrame(array_remodelado)
df = df.round (3)
print(df)

        0      1       2      3
0   2.600  2.200  34.460  0.250
1   0.500  1.610   1.480  5.870
2   0.500  0.700   2.600  2.200
3  34.460  0.250   0.500  1.610
4   1.480  5.870   0.500  0.700
5   7.908  2.126   7.908  2.126


## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [ ]:
medias_linhas = df.mean(axis=1)
df['Medias_Linhas'] = medias_linhas
print(df)

        0      1       2      3  Medias_Linhas
0   2.600  2.200  34.460  0.250         9.8775
1   0.500  1.610   1.480  5.870         2.3650
2   0.500  0.700   2.600  2.200         1.5000
3  34.460  0.250   0.500  1.610         9.2050
4   1.480  5.870   0.500  0.700         2.1375
5   7.908  2.126   7.908  2.126         5.0170


## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [ ]:
resumo = df.describe()
print("Resumo Estatistico")
print(resumo)
print("\nComparacao da ultima linha (indice 5):")
print(df.iloc[5, :4])

df_invertida = df.transpose()
print("\nDataFrame Invertida (Linhas viram Colunas)")
print (df_invertida)

Resumo Estatistico
               0        1          2        3  Medias_Linhas
count   6.000000  6.00000   6.000000  6.00000       6.000000
mean    7.908000  2.12600   7.908000  2.12600       5.017000
std    13.298569  1.99209  13.298569  1.99209       3.711003
min     0.500000  0.25000   0.500000  0.25000       1.500000
25%     0.745000  0.92750   0.745000  0.92750       2.194375
50%     2.040000  1.86800   2.040000  1.86800       3.691000
75%     6.581000  2.18150   6.581000  2.18150       8.158000
max    34.460000  5.87000  34.460000  5.87000       9.877500

Comparacao da ultima linha (indice 5):
0    7.908
1    2.126
2    7.908
3    2.126
Name: 5, dtype: float64

DataFrame Invertida (Linhas viram Colunas)
                     0      1    2       3       4      5
0               2.6000  0.500  0.5  34.460  1.4800  7.908
1               2.2000  1.610  0.7   0.250  5.8700  2.126
2              34.4600  1.480  2.6   0.500  0.5000  7.908
3               0.2500  5.870  2.2   1.610  0.70

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [ ]:
df.colums = ['Col_1', 'Col_2', 'Col_3', 'Col_4', 'Medias_Linhas']
df.index = ['Linha_1', 'Linha_2', 'Linha_3', 'Linha_4', 'Linha_5', 'Medias_Colunas']
media_das_medias = df.loc ['Medias_Colunas', 'Medias_Linhas']
print(df)

                     0      1       2      3  Medias_Linhas
Linha_1          2.600  2.200  34.460  0.250         9.8775
Linha_2          0.500  1.610   1.480  5.870         2.3650
Linha_3          0.500  0.700   2.600  2.200         1.5000
Linha_4         34.460  0.250   0.500  1.610         9.2050
Linha_5          1.480  5.870   0.500  0.700         2.1375
Medias_Colunas   7.908  2.126   7.908  2.126         5.0170
